### ISSUE TITLE
[offtopic] about hoyolab automation 

### ISSUE THREAD

**Issue by truong0235** [Sergiy3013/genshin_card#1]
since it was taken down due to github tos, will you bring it back in future?

**Comment by Sergiy3013** [comment]
GitHub removed this repository without warning or explanation, after my request they explained the reason for the removal:
![image](https://user-images.githubusercontent.com/35377469/216764363-37b74d98-28f6-4b0d-a2a0-89a7da730414.png)
I think I'll make a new version a bit later, maybe next weekend, but it won't work through requests like last time, but with browser emulation, since I haven't removed this repository.

**Comment by Sergiy3013** [comment]
If you're posting about it here, you're probably not from our discord server, if you want you can join and find a lot of useful information there. 
Here is a link valid for seven days, my nickname is **salem**
https://discord.gg/YPSpAxzg

**Comment by Sergiy3013** [comment]
Here is the new repository: https://github.com/Sergiy3013/genshin_daily_rewards
Here is a short instruction (almost the same as before): https://discord.com/channels/665827944425586700/980008184045527060/1074025371424538734

A little later I will make a full-fledged instruction as in the old repository. If you have any questions, feel free to contact me on our server.

**Comment by truong0235** [comment]
hi
so the genshin repo is down (again)
if possible, could you give us a tutorial how to make/host that repo by ourselves? since its taken down quite fast(er that the previous one, i think you or that repo are blacklisted)
